language: python
dist: xenial
matrix:
    include:
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
        - python: 3.8
          env: TOXENV=py38
        - python: 3.8
          env: TOXENV=pep8
        - python: 3.8
          env: TOXENV=mypy
        - python: pypy3
          env: TOXENV=pypy3

install:
    - pip install tox

script:
    tox

notifications:
    email: false
